### ISSUE TITLE
new contact without address will shut the app down

### ISSUE THREAD

**Issue by oddiccey001** [NewEconomyMovement/NEMiOSApp#179] opened 2016-04-03 17:58 UTC
[app shuts down.zip](https://github.com/NewEconomyMovement/NEMiOSApp/files/201471/app.shuts.down.zip)

When you created a contact the however not enter the address the app will shut down the next time you click on the contact you have created.

**Comment by Espo02** [comment] 2016-04-04 10:30
Yes, on my Iphone 5S it was the same.

**Comment by jabo38** [comment] 2016-04-04 10:31
@oddiccey001 what is your NEM address?

**Comment by LyubomirDominik** [comment] 2016-04-04 14:49
Could not reproduce

**Comment by oddiccey001** [comment] 2016-04-04 14:57
@jabo38 do you mean my real nem address or the test address I'm using for IOS wallet

**Comment by oddiccey001** [comment] 2016-04-04 14:57
@LyubomirDominik I have attached the quicktime video, hope you can view it

**Comment by LyubomirDominik** [comment] 2016-04-05 14:22
Fixed in Version 2 Build 32 BETA

**Comment by oddiccey001** [comment] 2016-04-07 22:39
NDKAZ7-JNVWWU-XI5FDG-2C5NR5-YDQW64-54MJR5-ODJQ

thanks for the reward
@LyubomirDominik @jabo38

**Comment by jabo38** [comment] 2016-05-11 15:23
Transaction hash: 5c9eca46cbf746a27202ccf3d463c4022ce51db5bf363e6d9144afca6aa3057c

Bounty paid.

**Comment by jabo38** [comment] 2016-06-11 19:27
fixed

**Closed by jabo38** 2016-06-11 19:27 UTC
Labels: bug, mustfix, resolved
