### ISSUE TITLE
App crashes.

### ISSUE THREAD

**Issue by Espo02** [NewEconomyMovement/NEMiOSApp#209] opened 2016-05-24 18:48 UTC
Here are some issues with app crashes.
Is it possible that all crashes have the same source?

https://github.com/NewEconomyMovement/NEMiOSApp/issues/203
https://github.com/NewEconomyMovement/NEMiOSApp/issues/188

The app is always instable if it has to load a lot of individual account informations. Is the error maybe a slow connection to the server? is the server to slow? crashes the app because it gets no data?

I have some test accounts on my Iphone and if I switch between them as fast as i can the app will crash.
... Its only a guess... 

Espo: NDEFC3-H4VAIU-FQ5GFT-IK3IJR-4DGKF7-PEQKRW-LPZ5

**Comment by Espo02** [comment] 2016-05-24 18:53
I Tested with NEMiOS2 BETA37

**Comment by jabo38** [comment] 2016-05-26 09:42
Confirmed here too.  https://github.com/NewEconomyMovement/NEMiOSApp/issues/211

**Comment by jabo38** [comment] 2016-05-26 09:45
When I had a phone, I also had problems with the app crashing here and there, I kept on trying to isolate the problem but had a hard time.

**Comment by Mehbsl** [comment] 2016-05-27 13:34
The problem for at least one crash is exactly what you thought, Espo02. To fetch the transaction history for an account the application needs the corresponding account address. Now, the problem is that often when the application wants to get the address for the account to later make the call to fetch the transaction history, the value of the account address is NIL (no address available) which then leads to a crash because the address variable gets force unwrapped. 

I can't get the application to run longer than 30 seconds because of this bug. I've attached a screenshot showing the breakpoint where the app crashes because the address variable is NIL.

![bildschirmfoto 2016-05-26 um 15 28 37](https://cloud.githubusercontent.com/assets/18571472/15609438/57d0bf14-2420-11e6-9016-ef563e46386c.png)

**Comment by Espo02** [comment] 2016-05-30 04:25
With a TestNIS Server in my Wifi and configured with the local IP the app doesn't crash.
I Think the most crashes of the App have the same source and a to small Bandwith isn't the Bug. My guess is, that there is something wrong with the error Handling if a Information comes to slow.

The same here: https://github.com/NewEconomyMovement/NEMiOSApp/issues/211

**Comment by fyahfox** [comment] 2016-05-30 17:10
@kmiliak What do you think about this?

**Comment by LyubomirDominik** [comment] 2016-06-10 13:21
Fixed in Version 2 Build 38

**Comment by Espo02** [comment] 2016-06-10 19:28
very good. The App diddn't crash. :+1:

**Closed** 2016-06-11 13:30 UTC
Labels: bug, mustfix, resolved

**Comment by jabo38** [comment] 2016-06-11 15:20
@Mehbsl what is your NEM account?

**Comment by jabo38** [comment] 2016-08-02 17:45
Bounty paid. Tx hash:b3cb036b6099ea2ed4431b4b37aca8f408f47fc16e431f73f653f595e480b22e
